DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'hotel') THEN
        CREATE SCHEMA hotel;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS hotel."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'hotel') THEN
            CREATE SCHEMA hotel;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."AspNetUsers" (
        "Id" uuid NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."RoomTypes" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(4000) NOT NULL,
        "BasePrice" numeric(12,2) NOT NULL,
        "Capacity" integer NOT NULL,
        "BedCount" integer NOT NULL,
        "SizeInSquareMeters" integer NOT NULL,
        "Amenities" character varying(1000) NOT NULL,
        "ImageUrls" character varying(8000) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_RoomTypes" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_RoomType_Values" CHECK ("BasePrice" > 0 AND "Capacity" > 0 AND "BedCount" > 0 AND "SizeInSquareMeters" > 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES hotel."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES hotel."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES hotel."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES hotel."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES hotel."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES hotel."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."Rooms" (
        "Id" uuid NOT NULL,
        "Number" character varying(12) NOT NULL,
        "Floor" integer NOT NULL,
        "RoomTypeId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Rooms_RoomTypes_RoomTypeId" FOREIGN KEY ("RoomTypeId") REFERENCES hotel."RoomTypes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."Reservations" (
        "Id" uuid NOT NULL,
        "Code" character varying(32) NOT NULL,
        "CustomerId" uuid NOT NULL,
        "RoomId" uuid NOT NULL,
        "RoomTypeId" uuid NOT NULL,
        "RoomTypeName" character varying(100) NOT NULL,
        "RoomNumber" character varying(12) NOT NULL,
        "CheckInDate" date NOT NULL,
        "CheckOutDate" date NOT NULL,
        "GuestCount" integer NOT NULL,
        "GuestName" character varying(100) NOT NULL,
        "GuestPhone" character varying(30) NOT NULL,
        "NightlyPrice" numeric(12,2) NOT NULL,
        "TotalPrice" numeric(14,2) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "Status" integer NOT NULL,
        "ActualCheckInUtc" timestamp with time zone,
        "ActualCheckOutUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Reservation_Values" CHECK ("CheckOutDate" > "CheckInDate" AND "GuestCount" > 0 AND "TotalPrice" >= 0),
        CONSTRAINT "FK_Reservations_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES hotel."AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Reservations_RoomTypes_RoomTypeId" FOREIGN KEY ("RoomTypeId") REFERENCES hotel."RoomTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Reservations_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES hotel."Rooms" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."RoomJobs" (
        "Id" uuid NOT NULL,
        "RoomId" uuid NOT NULL,
        "Kind" integer NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "CompletedAtUtc" timestamp with time zone,
        "CompletedBy" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_RoomJobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoomJobs_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES hotel."Rooms" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE TABLE hotel."Reviews" (
        "Id" uuid NOT NULL,
        "ReservationId" uuid NOT NULL,
        "Rating" integer NOT NULL,
        "Comment" character varying(1500) NOT NULL,
        "IsApproved" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Review_Rating" CHECK ("Rating" BETWEEN 1 AND 5),
        CONSTRAINT "FK_Reviews_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES hotel."Reservations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON hotel."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON hotel."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON hotel."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON hotel."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON hotel."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE UNIQUE INDEX "EmailIndex" ON hotel."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON hotel."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Reservations_Code" ON hotel."Reservations" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_Reservations_CustomerId_CreatedAtUtc" ON hotel."Reservations" ("CustomerId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_Reservations_RoomId_Status_CheckInDate_CheckOutDate" ON hotel."Reservations" ("RoomId", "Status", "CheckInDate", "CheckOutDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_Reservations_RoomTypeId" ON hotel."Reservations" ("RoomTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Reviews_ReservationId" ON hotel."Reviews" ("ReservationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_RoomJobs_RoomId_CompletedAtUtc" ON hotel."RoomJobs" ("RoomId", "CompletedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Rooms_Number" ON hotel."Rooms" ("Number");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    CREATE INDEX "IX_Rooms_RoomTypeId" ON hotel."Rooms" ("RoomTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM hotel."__EFMigrationsHistory" WHERE "MigrationId" = '20260909122701_InitialCreate') THEN
    INSERT INTO hotel."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260909122701_InitialCreate', '10.0.9');
    END IF;
END $EF$;
COMMIT;

